version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
  pre_build:
    commands:
      - echo Starting pre_build phase
  build:
    commands:
      - echo Deploying app to EC2
      - scp -o StrictHostKeyChecking=no -i /root/.ssh/my-key.pem -r * ec2-user@3.107.173.84:/home/ec2-user/app
      - ssh -o StrictHostKeyChecking=no -i /root/.ssh/my-key.pem ec2-user@3.107.173.84 "cd /home/ec2-user/app && npm install && nohup node index.js &"

artifacts:
  files:
    - '**/*'
