name: CI/CD to EC2

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint || echo "Skipping lint"

      - name: Run tests
        run: npm test || echo "Skipping tests"

      - name: Write SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy code to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no -r * ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} "
          cd /home/ec2-user/app &&
          npm install &&
          nohup node index.js &
          "
